### ISSUE TITLE
ignoring #pragma warning disable

### ISSUE THREAD

**Issue by jafarsoltani** [liamkf/Unreal_FASTBuild#12]
Hello,
Compiling UE, I get the following error VisualStudioSourceCodeAccessor.cpp:
`warning C4278: 'GetObject': identifier in type library '80cc9f66-e7d8-4ddd-85b6-d9e6cd0e93e2' is already a macro; use the 'rename' qualifier`

but looking at the code it has the following line just above it:
`#pragma warning(disable: 4278)`
which seems like it's somehow ignoring it?

**Comment by jafarsoltani** [comment]
I should also add that this seems to be happening when I'm using local cache, if I don't specify a cache it's all fine.

**Comment by liamkf** [comment]
Did you ever sort out what the issue was here? I don't think I've ever seen this pop up.
