### ISSUE TITLE
Network distribution fails on copying files with spaces in the directory path

### ISSUE THREAD

**Issue by jackknobel** [liamkf/Unreal_FASTBuild#18]
Not sure if this is specific to this implementation or FastBuild itself but when it tries to copy to a directory containing a space it fails.

The directory being:
> C:\Pine Fire Studios\Project\Engine\Engine\Source\

It fails with one of two errors:
1)
`3>Fire
3>c1xx : fatal error C1083: Cannot open source file: 'Fire': No such file or directory
3>c1xx : fatal error C1083: Cannot open source file: 'Studios\Project\Engine\Engine\Source\': No such file or directory
3>Fire
3>c1xx : fatal error C1083: Cannot open source file: 'Fire': No such file or directory
3>c1xx : fatal error C1083: Cannot open source file: 'Studios\Project\Engine\Engine\Source\': No such file or directory
3>Fire`
`
2)
https://hastebin.com/axecavodaj.tex

I've tried changing how the copy action source and destination is handled but it seems to have no affect.
Any suggestions?

Thanks!

**Comment by AlanIWBFT** [comment]
FASTBuild doesn't like the space between /I and "path/to/file". When it builds locally this is fine. So my workaround is to remove all the spaces when loading from the response file.

**Comment by ffulin** [comment]
This may be related to: https://github.com/fastbuild/fastbuild/issues/343

If it's a different issue, it'd be great to work out if this is because of the way the bff is being generated, or a bug in FASTBuild itself. Either way it's something that is likely easily fixed.

**Comment by jackknobel** [comment]
Hey @ffulin, that's interesting. Thanks for checking in on this issue!
