### ISSUE TITLE
Linkage fails on UE4 4.15 Xbox One

### ISSUE THREAD

**Issue by MazingR** [liamkf/Unreal_FASTBuild#23]
Hello,

I'm getting a link error with UE4.15 ThirdParty PhysX library, as if the .lib was missing.
Of course the file is there and compilation without FastBuild works fine.

I basicaly get this error  :  

`3>LINK : fatal error LNK1181: cannot open input file 'PhysX3PROFILE.lib'

....

3>ERROR : UBT error : Failed to produce item: .
...
`

Thanks for the help.

**Comment by yass007** [comment]
Can you try the latest please? 
If you can upgrade to 4.18 :).

**Comment by yass007** [comment]
Closing since 4.18 and 4.19 have been pushed with XBox One support.
