### ISSUE TITLE
 warning LNK4042: object specified more than once

### ISSUE THREAD

**Issue by oliviergaertner** [liamkf/Unreal_FASTBuild#25]
Hey Guys!

We are currently upgrading from 4.15 to 4.18 and with the lattest fastbuild we are seing this warning:

 warning LNK4042: object specified more than once

Do you have the same behavior?

Cheers,

Olivier

**Comment by yass007** [comment]
Hi Olivier, Yes we do have that annoying but harmless warning. I will be looking into it.

**Comment by oliviergaertner** [comment]
Good to know I thought it was an issue on our side :)

**Comment by yass007** [comment]
Fixed

**Comment by Ross9000** [comment]
> 
> 
> Fixed

What do you mean with fixed? I'm having the same issue using fastbuild 1.00, vs2015 and windows 7, please explain it, thank you.
