### ISSUE TITLE
PS4 broken in 4.18

### ISSUE THREAD

**Issue by oliviergaertner** [liamkf/Unreal_FASTBuild#26]
Hey Guys!

The PS4 build is broken in 4.18. From what I can see the dependcies seem to be broken. It looks like I have some modules depending on others that are trying to link before the second one is linked.

I've also tryed to only link the final exe and it looks like the dependencies to the SDK librairies are missing.

If you have any idea I can have a look at Fastbuild.cs but I'm not familiar with UBT system at all :(

Cheers,

Olivier

**Comment by yass007** [comment]
Hi Olivier,
Unfortunately we are not in the capacity to support PS4 in the short term, although I know that many people were able to make it work by modifying the existing code.

We hope to do a PS4 pass soon, until then I suggest to use SNDBS if you can.

Cheers.
