### ISSUE TITLE
Android/iOS support?

### ISSUE THREAD

**Issue by thunder-spb** [liamkf/Unreal_FASTBuild#27]
Hi @liamkf .

Does this class supports Android and iOS builds? Getting alot of errors like:
for Adnroid
```
UnrealBuildTool: We have no OutputObjectFileName. Bailing.
UnrealBuildTool: We failed to find /fo, which may be a problem.
```
for iOS
```
UnrealBuildTool: Failed to find output file. Bailing.
UnrealBuildTool: We failed to find /OUT:, which may be a problem.
```

iOS build compiled on remote Mac with xcode clang++ for example...

**Comment by liamkf** [comment]
Hi there!

I'm afraid it's currently set up only for Windows and Xbox. Building for Mac/iOS/Android is not supported as we haven't been on those platforms for a while.

It should be possible to add support for them if you're inclined though! Off the top of my head, you'd need to add new build types, modify the WriteEnvironmentSetup to write out the correct compiler information, and then update ParseCommandLineOptions to ensure it is pulling out the correct information to pass on to fastbuild. It did support PS4 briefly, so hopefully at least some of the clang options would already parse correctly.

Hope this helps!

**Comment by thunder-spb** [comment]
thanks @liamkf ! you did a great job!
