### ISSUE TITLE
FASTBuild not used when compiling the engine using BuildGraph?

### ISSUE THREAD

**Issue by TheEmidee** [liamkf/Unreal_FASTBuild#28]
Hello,

I have no problem compiling UE4 in VS2017 with FASTBuild. All the work is being correctly distributed to all the workers of the pool.

But when I want to compile the engine using BuildGraph, using that command-line for example:

`F:/Projects/ConsoleDev/UnrealEngine/Engine/Build/BatchFiles/RunUAT.bat BuildGraph -target="Make Installed Build Win64"  -set:WithDDC=false -set:WithFeaturePacks=false -set:WithWin64=true -set:WithPS4=true -set:WithSwitch=true -set:WithXboxOne=true -set:WithTVOS=false -set:WithLinux=false -set:WithIOS=false -set:WithAndroid=false -set:WithMac=false -set:WithHTML5=false -set:WithWin32=false -set:OutputDirectoryOverride=F:/ShiftQuantumBuilds/UE4 -script="F:/Projects/ConsoleDev/UnrealEngine/Engine/Build/InstalledEngineBuild.xml" `

FASTBuild is not used. 

Is there something missing in the provided CS file to have FASTBuild triggered?

Thanks !

**Comment by liamkf** [comment]
Hi there!

I don't have any experience with using the BuildGraph I'm afraid. But I imagine if it's building the code it will eventually have to call UnrealBuildTool, which if it's been modified should use FASTBuild where appropriate. I would try to see where UnrealBuildTool is launched from the automation tool when using BuildGraph and see the parameters, then try debugging UnrealBuildTool itself with those parameters if nothing seems obviously wrong.

Sorry I can't be more help!

Cheers,
Liam

**Comment by TheEmidee** [comment]
I found out the problem is in UE4Build.cs

The function `public bool CanUseXGE(UnrealBuildTool.UnrealTargetPlatform Platform)` returned always true, and the code which uses that function is flawed, in the sense it does not try anything else than XGE if the function returns true.

As a quick workaround I made that function return false and now FastBuild is correctly used when using buildgraph
