### ISSUE TITLE
Complete example with FASTBuild

### ISSUE THREAD

**Issue by fire** [liamkf/Unreal_FASTBuild#3]
I've made a complete example of FASTBuild for Unreal Engine with an ENV variable name FASTBUILD_CACHE telling where the cache folder is for build server purposes.

Hopefully this is useful for someone.

[EnableFastbuild.diff.txt](https://github.com/liamkf/Unreal_FASTBuild/files/439449/EnableFastbuild.diff.txt)

**Comment by liamkf** [comment]
Hi there, that's awesome! 

Thanks for sharing it, I hope it helps someone along! :)
