### ISSUE TITLE
Working setup for UE 4.21

### ISSUE THREAD

**Issue by ricekab** [liamkf/Unreal_FASTBuild#31]
I've spent the last couple weeks (on and off) getting FastBuild to work with UE 4.21. I've included my setup in the gist below, hopefully it's useful to someone before 4.22 undoubtedly breaks something again.

This was testing with a complete clean & rebuild with a slightly modified version of UE 4.21 . **I have not tested this configuration with any FastBuild caching**.

An overview of the changes and additions:

* Created some extension methods for VCEnvironment to patch things that were removed or changed from 4.19 . Some of the solutions in here aren't very clean and may require some retooling. I placed this under `UnrealBuildTool\Platform\Windows\VCEnvironmentFastbuildExtensions.cs` (See gist for code).
* Set `bEnableUndefinedIdentifiedWarnings` to false in `UnrealBuildTool\Configuration\ModuleRules.cs`. This was breaking compilation with Windows 10 SDK. (See gist for code).
* Added an action to support `ActionType.BuildProject` in `FASTBuild.cs`. This may not work for everything. I've only seen this action type used for copying files so that is what it does in the BFF file. FASTbuild.cs also modified to work with modified VCEnvironment.
* ActionGraph and BuildConfiguration required no changes compared to 4.19 .

View changes in code: https://gist.github.com/RiceKab/60d7dd434afaab295d1c21d2fe1981b0

**Comment by yass007** [comment]
Thanks!
You might want to try it out the new version that works for us on all platforms (UE 4.21.1). No caching.

**Comment by ricekab** [comment]
Thanks for the update. I'll try and get around to testing it sometime next week.

**Comment by ttvd** [comment]
Do you guys have distributed xbox one compilation working? I updated the previous version and made it work with 4.21; it seems to compile fine on the master machine, but it fails to distribute.

**Comment by BrodyHiggerson** [comment]
@yass007 to clarify, when you say "No caching", do you mean caching is not tested, or that caching is definitely _not_ working? It seems like a pretty handy feature.

**Comment by ricekab** [comment]
I recall seeing it mentioned somewhere that it is just not tested. I haven't gotten around to checking it myself yet.

EDIT: Regarding Xbox compilation. It's not one of our targets so I've never tried it.

**Comment by liamkf** [comment]
Hi there! We just haven't run with caching recently, I don't see why it couldn't be working though... :)

As far as Xbox distribution goes, https://github.com/fastbuild/fastbuild/issues/363 and https://github.com/fastbuild/fastbuild/issues/438 still remain in effect unfortunately...

**Comment by ricekab** [comment]
A bit of a late response but better than never :D 

We have a setup where we're caching on a shared network drive and that seems to be working without a problem. In the rare case where the cache seems to fail it seems to just continue with normal (non-cached) behaviour.

**Comment by ttvd** [comment]
It does look like it will take significant amount of effort to get xb1 working with fastbuild due to /zw. PCH and the fact that some core modules have to be compiled with /zw complicates things.
