### ISSUE TITLE
error in buld Development

### ISSUE THREAD

**Issue by RPG3D** [liamkf/Unreal_FASTBuild#33]
Hi, I using UE4.21.1 & FastBuild0.9.6, I can compile Engine(UE4Editor) correctly, however, it cannot build project exe. switch config to Development, Win64, the link exe eats much ram, ram totall used up to 99%.

**Comment by yass007** [comment]
We just pushed a new version of the integration that works with 4.21.1, You might want to give it a shot and let us know if it gets you passed your issue. 

P.S: It would be odd that a FASTBuild regression could have caused the RAM usage issue. We'll upgrade to v0.96 at some point in the future but no ETA.
