### ISSUE TITLE
Doesn't work in 4.13 - Compile actions are response files

### ISSUE THREAD

**Issue by fire** [liamkf/Unreal_FASTBuild#4]
In 4.13 the compile files are response files rather than ordinary arguments. Just a heads up to changes in the future.

**Comment by fire** [comment]
4.13 has released. https://github.com/epicgames/unrealengine/tree/4.13

**Comment by liamkf** [comment]
Hi, thanks for the report! I'll sync the latest Unreal and see what can be done. :)

**Comment by liamkf** [comment]
Ok I've pushed a change to allow it to work with 4.13's default behaviour here [https://github.com/liamkf/Unreal_FASTBuild/commit/8285d1c0aee4df24b7a5ad1d694c3b5be75f75f5#diff-4582a3d8c09dcb4a7c9b2fde4f9a41bc](url) which allows it to build fine.

As mentioned in the check-in comment it may be preferable to modify VCToolChain.cs instead to not use reponse files, particularly given Epic only made the change to support XGE! :)

Thanks again for the report!
